name: CI
on: [push]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get install -y cmake
    - run: for d in formatter_lib formatter_ex_lib hello_world solver; do cd $d && cmake -H. -B_build && cmake --build _build && cd ..; done
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        cd formatter_lib; cmake -H. -B_build; cmake --build _build
        cd ../formatter_ex_lib; cmake -H. -B_build; cmake --build _build
        cd ../hello_world; cmake -H. -B_build; cmake --build _build
        cd ../solver; cmake -H. -B_build; cmake --build _build
